CREATE TABLE question
(
    ID INT AUTO_INCREMENT,
    TITLE VARCHAR(50),
    DESCRIPTION TEXT,
    GMT_CREATE BIGINT,
    GMT_MODIFIED BIGINT,
    CREATOR INT,
    COMMENT_COUNT INT DEFAULT 0,
    VIEW_COUNT INT DEFAULT 0,
    LIKE_COUNT INT DEFAULT 0,
    TAG VARCHAR(256),
    CONSTRAINT QUESTION_PK
        PRIMARY KEY (ID)
);

